-- MySQL Script generated by MySQL Workbench
-- Tue Jan 24 01:23:10 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Pessoa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Pessoa` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` CHAR(20) NOT NULL,
  `sobrenome` CHAR(30) NOT NULL,
  `cpf` CHAR(14) NOT NULL,
  `data_nascimento` DATE NOT NULL,
  `numero_de_telefone` CHAR(17) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Clientes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `rua` CHAR(50) NOT NULL,
  `logradouro` CHAR(50) NOT NULL,
  `setor` CHAR(50) NOT NULL,
  `Pessoa_id` INT NOT NULL,
  PRIMARY KEY (`id`, `Pessoa_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_Clientes_Pessoa1_idx` (`Pessoa_id` ASC) VISIBLE,
  CONSTRAINT `fk_Clientes_Pessoa1`
    FOREIGN KEY (`Pessoa_id`)
    REFERENCES `mydb`.`Pessoa` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Funcionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Funcionario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `funcao` CHAR(50) NOT NULL,
  `Pessoa_id` INT NOT NULL,
  `Pessoa_id1` INT NOT NULL,
  PRIMARY KEY (`id`, `Pessoa_id1`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_Funcionario_Pessoa1_idx` (`Pessoa_id1` ASC) VISIBLE,
  CONSTRAINT `fk_Funcionario_Pessoa1`
    FOREIGN KEY (`Pessoa_id1`)
    REFERENCES `mydb`.`Pessoa` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Atendimento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Atendimento` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Horario` DATETIME NOT NULL,
  `detalhes` MEDIUMTEXT NOT NULL,
  `criado_em` DATETIME NOT NULL,
  `atualizado_em` DATETIME NOT NULL,
  `reagendado` TINYINT NOT NULL DEFAULT 0,
  `Funcionario_id` INT NOT NULL,
  `Clientes_id` INT NOT NULL,
  PRIMARY KEY (`id`, `Funcionario_id`, `Clientes_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_Atendimento_Funcionario1_idx` (`Funcionario_id` ASC) VISIBLE,
  INDEX `fk_Atendimento_Clientes1_idx` (`Clientes_id` ASC) VISIBLE,
  CONSTRAINT `fk_Atendimento_Funcionario1`
    FOREIGN KEY (`Funcionario_id`)
    REFERENCES `mydb`.`Funcionario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Atendimento_Clientes1`
    FOREIGN KEY (`Clientes_id`)
    REFERENCES `mydb`.`Clientes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
